variables:
  source_dir: src/main/php
  test_dir: src/test/php
  build_dir: build
  vendor_dir: vendor
  bin_dir: $vendor_dir/bin
  php_base_image: $CI_REGISTRY/devops/docker-webservers/php-fpm-ci:1.6.0

default:
  image: $php_base_image
  cache:
    key: php7
    paths:
      - $build_dir
      - $vendor_dir
  tags:
    - docker

stages:
  - prepare
  - analyse
  - test
  - docgen
  - artifacts

prepare:
  stage: prepare
  script:
    - composer install --prefer-dist
    - mkdir -p $build_dir/api $build_dir/coverage $build_dir/logs

lint:
  stage: analyse
  script:
    - php -l $source_dir $test_dir

analyse:
  stage: analyse
  script:
    - rm -rf $build_dir/logs/*
    - $bin_dir/phpcs --report=full --report-checkstyle=$build_dir/logs/checkstyle.xml --standard=PSR12 --extensions=php --ignore=bootstrap.php $source_dir $test_dir
    - $bin_dir/phpcpd --log-pmd $build_dir/logs/pmd-cpd.xml $source_dir
    - $bin_dir/phploc --count-tests --log-xml=$build_dir/logs/phploc.xml --names-exclude=bootstrap.php $source_dir $test_dir

test:
  stage: test
  script:
    - rm -rf $build_dir/coverage/*
    - cp phpunit.xml.dist phpunit.xml
    - $bin_dir/simple-phpunit --configuration phpunit.xml

artifacts:
  stage: artifacts
  script:
    - echo "Generating artifacts..."
  artifacts:
    paths:
      - $build_dir
